---
- name: Install Morio on the EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Download and install Morio
      shell: |
        curl https://install.morio.it/ | bash && wait
      register: result
      args:
        executable: /bin/bash

    - name: Show installation result
      debug:
        msg: "{{ result.stdout }}"