---
- name: Stop Morio on the EC2 instances
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Stop Morio service
      ansible.builtin.systemd:
        name: moriod
        state: stopped
      ignore_errors: true
      register: stop_result

    - name: Log result of stopping Morio service
      debug:
        msg: "Morio service stop result: {{ stop_result.stdout | default('No output') }}"
