name: On-demand end-to-end tests

on:
  issue_comment:
    types: [created]

jobs:
  test:
    # Since issue_comment triggers for comments on both issues and pull requests
    # we need to make sure this is a command on a pull request
    if: |
      github.event.issue.pull_request &&
      contains(fromJSON('["joostdecock", "serge-tellene", "levente232"]'), github.event.comment.user.login) && contains(github.event.comment.body, vars.ITEST_DEPLOY_TRIGGER)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}

      - name: Run end-to-end tests
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ github.token }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
          COMMENT_URL: ${{ github.event.comment.html_url }}
        run: ./.github/workflows/run-e2e-tests.sh
