name: On-demand end-to-end tests

on:
  issue_comment:
    types: [created]

jobs:
  test:
    # Since issue_comment triggers for comments on both issues and pull requests
    # we need to make sure this is a command on a pull request
    if: |
      github.event.issue.pull_request &&
      contains(fromJSON('["joostdecock", "serge-tellene", "levente232"]'), github.event.comment.user.login) && contains(github.event.comment.body, 'do magic')
    runs-on: ubuntu-latest
    steps:
      - name: Run end-to-end tests
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: ./.github/workflows/run-e2e-tests.sh
