#
# This runs unit tests for the core and api in CI
# To run these tests locally, you can run the following:
#
# - npm run test:core
# - npm run tsest:api
#
# Make sure to do so in the repository root
#
name: Run unit tests
on:
  pull_request:

jobs:
  test:
    # This needs to run on a self-hosted runner
    # I also need a PR to make this work so here we go with a pointless change
    runs-on: self-hosted
    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}

      - name: Run unit tests
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ github.token }}
          COMMENT_AUTHOR: ${{ github.event.comment.user.login }}
          COMMENT_URL: ${{ github.event.comment.html_url }}
        run: ./.github/workflows/unit-tests.sh
