#
# This runs unit tests for the core and api in CI
# To run these tests locally, you can run the following:
#
# - npm run test:core
# - npm run tsest:api
#
# Make sure to do so in the repository root
#
name: Run unit tests
permissions:
  contents: read
  pull-requests: write
on:
  pull_request:
    branches: [develop]

jobs:
  test:
    # This needs to run on a self-hosted runner
    # we need a change
    runs-on: self-hosted
    steps:
      # Remove the data directory before checking out the code
      - name: Remove data directory if it exists
        run: |
          sudo rm -rf ./data || echo "No data directory to remove"

      - name: Checkout PR Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.event.issue.pull_request.head.sha }}

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Install dependencies
        run: npm ci

      - name: Configure repository
        env:
          MORIO_FQDN: runner.morio.it
          GIT_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.id }}
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: npm run reconfigure

      - name: Build docker images for local development
        run: npm run buildall:dev

      - name: Run Core unit tests
        env:
          MORIO_FQDN: runner.morio.it
          GIT_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.id }}
        run: npm run test:core

      - name: Run API unit tests
        env:
          MORIO_FQDN: runner.morio.it
          GIT_COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.id }}
        run: npm run test:api
